@ECHO OFF
SET FORMATOUT=%~p0\formatout.cmd
CALL:RandomColor %1 %2
:Done
GOTO :Done

:RandomColor
SETLOCAL ENABLEDELAYEDEXPANSION
SET /a LETTER=(%Random% %%6)+1
SET /a NUMBER=(%Random% %%9)+1
GOTO :CASE_!LETTER!
:CASE_1
  SET RETURN=A
  GOTO :END_CASE
:CASE_2
  SET RETURN=B
  GOTO :END_CASE
:CASE_3
  SET RETURN=C
  GOTO :END_CASE
:CASE_4
  SET RETURN=D
  GOTO :END_CASE
:CASE_5
  SET RETURN=E
  GOTO :END_CASE
:CASE_6
  SET RETURN=F
  GOTO :END_CASE
:END_CASE

ENDLOCAL && set "RETURN_COLOR=%return%" && SET "NUMBER=%NUMBER%"
IF DEFINED RETURN_COLOR (
  COLOR %NUMBER%%RETURN_COLOR%
  ECHO COLOR %NUMBER%%RETURN_COLOR%
)
GOTO:EOF

:FORMATOUT
  CALL %FORMATOUT% %~1 %~2 "%~3" "%~4%~5%~6"
GOTO:EOF

:Done